ProntoAtendimento/Models/Procedimento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProntoAtendimento.Models
{
    public class Procedimento
    {
        public int? IdProcedimento { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Campo nome obrigatório")]
        [MinLength(3)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo procedimento obrigatório")]
        public string Tipo { get; set; }

        

        [Display(Name = "Valor")]
        [Required(ErrorMessage = "Campo valor obrigatório")]
        [DataType(DataType.Currency)]
        public decimal Valor { get; set; }        
    }
}

ProntoAtendimento/Controllers/ProcedimentoController.cs
using ProntoAtendimento.Data;
using ProntoAtendimento.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProntoAtendimento.Controllers
{
    //Um controlador é apenas uma classe que deriva (herda) da classe base
    //System.Web.Mvc.Controller.  Como um controlador herda dessa classe
    //base, um controlador herda vários métodos úteis
    public class ProcedimentoController : Controller
    {
        //O IAction tipo de retorno é apropriado quando vários  ActionResult
        //tipos de retorno são possíveis em uma ação
        //Os tipo AcrionResult representam vários códigos de status HTTP
        public IActionResult Index()
        {
            //Criando um objeto data da classe ProdutoData
            using (var data = new ProcedimentoData())
                return View(data.Read());
            //data.Read() chama a execução do método Read (Select + From Produtos)
        }

        public IActionResult Selection()
        {
            //Criando um objeto data da classe ProdutoData
            using (var data = new ProcedimentoData())
                return View(data.Read());
            //data.Read() chama a execução do método Read (Select + From Produtos)
        }


        [HttpGet]
        public IActionResult Create()
        {
            //ViewBag tem como objetibo trasnportar pequenas quantidades de dados
            //entre views ou de controllers para views
            

            return View();
        }

        // A ideia geral é a seguinte: seu serviço vai prover uma url base
        // e os verbos HTTP vão indicar qual ação está sendo requisitada pelo
        // consumidor do serviço. Por exemplo, considerando a URL
        // www.dominio.com/rest/notas/, se enviarmos para ela uma requisição
        // HTTP utilizando o verbo GET, provavelmente obteremos como resultado
        // uma listagem de registros(notas, nesse caso). Por outro lado,
        // se utilizarmos o verbo POST, provalmente estaremos tentando adicionar
        // um novo registro, cujos dados serão enviados no corpo da requisição.

        [HttpPost]
        public IActionResult Create(Procedimento procedimento)
        {
            //O ModeState é uma propriedade da classe Controller e pode ser
            //acessada a partir das classes que herdam de System.Web.Mvc.Controller.
            //Ele representa uma coleção de pares nome/valor que são submetidos
            //ao servidor durante o POST e também contém uma coleção de mensagens
            //de erros para cada calor submetido
            if (!ModelState.IsValid)
            {
                return View(procedimento);
            }

            if (procedimento.Valor < 0)
            {
                ViewBag.Message = "O Valor deve ser maior que 0";
                return View();
            }


            using (var data = new ProcedimentoData())
                data.Create(procedimento);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            ItensUtilizados procUtizas = new ItensUtilizados();
            if(procUtizas.IdProcedmento == id)
            {
                using (var data = new ProcedimentoData())
                    data.Delete(id);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Mensagem = "O procedimento não foi utilizado";
                return View("Index");
            }
        }

        [HttpGet]
        public IActionResult Update(int id)
        {           
            using (var data = new ProcedimentoData())
                return View(data.Read(id));
        }

        [HttpPost]
        public IActionResult Update(int id, Procedimento procedimento)
        {
            try
            {
                if (procedimento.Valor < 0)
                {
                    ViewBag.Message = "Valor inválido.";
                    using (var data = new ProcedimentoData())
                        return View(data.Read(id));
                }

                    procedimento.IdProcedimento = id;

                    if (!ModelState.IsValid)
                    {
                        return View(procedimento);
                    }

                    using (var data = new ProcedimentoData())
                        data.Update(procedimento);

                    return RedirectToAction("Index");
                
            }
            catch (Exception es)
            {
                ViewBag.Message = "CPF e/ou Login já cadastrado";
                return View();


            }

        }
    }
}

ProntoAtendimento/Views/Procedimento/Create.cshtml
@model Procedimento

@if (ViewBag.Message != null)
{
<div class="alert alert-danger">@ViewBag.Message</div>}


<form asp-controller="Procedimento" asp-action="Create" method="POST">
    <h2>Cadastrar Procedimento</h2>
    <br />
    <div class="form-group">
        <label>Nome</label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome"></span>
    </div>

    <div class="form-group">
        <label>Tipo</label>
        <select asp-for="Tipo" class="form-control">
            <option value="1">Ambulatorial</option>
            <option value="2">Laboratorial</option>
            <option value="3">Translado</option>
        </select>
    </div>

    <div class="form-group">
        <label>Valor</label>
        <input asp-for="Valor" class="form-control" />
        <span asp-validation-for="Valor"></span>
    </div>



    <button class="btn btn-primary">Salvar</button>
</form>

ProntoAtendimento/Views/Procedimento/Index.cshtml
@model List<Procedimento>

@{

    ViewData["Title"] = "Produto - Index";
}


@if (ViewBag.Message != null)
{
    <div class="alert alert-danger">@ViewBag.Message</div>
}

<h5>Lista de Procedimentos</h5>

<table class="table table-hover rounded-top rounded-bottom shadow">

    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Tipo</th>
        <th>Valor</th>

    </tr>
    @foreach (var proced in Model)

    {
        <tr>
            <td>@proced.IdProcedimento</td>
            <td>@proced.Nome</td>
            <td>@proced.Tipo</td>
            <td>@proced.Valor</td>

            <td>
                <a class="btn btn-sm btn-danger" href="/procedimento/delete/@proced.IdProcedimento">Apagar</a>
                <a class="btn btn-sm btn-warning" href="/procedimento/update/@proced.IdProcedimento">Editar</a>


            </td>

        </tr>
    }
</table>
<a class="btn btn-info cart-btn-transform mt-2 float-right m-2" href="/procedimento/create/">Adcionar</a>
<a class="btn btn-primary" href="/home/editar">Voltar</a>

ProntoAtendimento/Views/Procedimento/Selection.cshtml
@model List<Procedimento>

@{

    ViewData["Title"] = "Produto - Index";
}
<h5>Procedimentos</h5>

<table class="table table-hover rounded-top rounded-bottom shadow">

    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Tipo</th>
        
        
    </tr>
    @foreach (var proced in Model)

    {
        <tr>
            <td>@proced.IdProcedimento</td>
            <td>@proced.Nome</td>
            <td>@proced.Tipo</td>
            
            
            <td>
                
                <a class="btn btn-sm btn-info" href="/listaprocedimentos/escolher/@proced.IdProcedimento">Escolher</a>
            </td>

        </tr>
    }
</table>
<a class="btn btn-primary" href="/consulta/atender">Voltar</a>

ProntoAtendimento/Views/Procedimento/Update.cshtml
@model Procedimento

@if (ViewBag.Message != null)
{
<div class="alert alert-danger">@ViewBag.Message</div>}


<form asp-controller="Procedimento" asp-action="Update" method="POST">
    <h2>Editar Procedimento</h2>
    <br />
    <div class="form-group">
        <label>Nome</label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome"></span>
    </div>

    <div class="form-group">
        <label>Tipo</label>
        <select asp-for="Tipo" class="form-control">
            <option value="1">Ambulatorial</option>
            <option value="2">Laboratorial</option>
            <option value="3">Translado</option>
        </select>
    </div>

    <div class="form-group">
        <label>Valor</label>
        <input asp-for="Valor" class="form-control" />
        <span asp-validation-for="Valor"></span>
    </div>



    <button class="btn btn-primary">Salvar</button>
</form>