ProntoAtendimento/Models/Consulta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;


namespace ProntoAtendimento.Models
{
    public class Consulta
    {
        //Propriedades e Atributos
        public int Nr { get; set; }
        public int IdPaciente { get; set; }
        
        public int IdAtendente { get; set; }
        public int IdMedico { get; set; }
        public string NomePaciente { get; set; }
        public string NomeMedico { get; set; }
        public string NomeAtendente { get; set; }
        public DateTime Data { get; set; }
        public List<ItensUtilizados> Procedimentos { get; set; } = new List<ItensUtilizados>();
        /* public decimal Valor 
         {
             get
             {
                 return Procedimentos.Sum(i => i.ValorTotal);
             }

             set { Valor = value; }
         }*/
        public decimal Valor { get; set; }        
        
        public string Status { get; set; }

        [Required(ErrorMessage = "Campo Diagnóstico obrigatório")]
        public string Diagnostico { get; set; }

        public Paciente Paciente { get; set; }
        public Medico Medico { get; set; }


    }
}

ProntoAtendimento/Controllers/ConsultaController.cs
using Microsoft.AspNetCore.Mvc;
using ProntoAtendimento.Data;
using ProntoAtendimento.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.Text.Json;



namespace ProntoAtendimento.Controllers
{
    public class ConsultaController : Controller
    {
        public IActionResult Index(Consulta novaConsulta)
        {
            using (var data = new ConsultaData())
            return View(data.ReadAll());
        }


        public IActionResult Fim()
        {
            
                return View();
        }

        public IActionResult Erro()
        {
            return View();
        }

        public IActionResult Atender(Consulta novaConsulta)
        {
            var medico = HttpContext.Session.GetString("user2");
            Medico novomedico = System.Text.Json.JsonSerializer.Deserialize<Medico>(medico);

            using (var data = new ConsultaData())
                return View(data.Read((int)novomedico.Id));
        }


        public IActionResult RelatorioPaciente()
        {



            //HttpContext.Session.SetString("pacienterelatorio", JsonSerializer.Serialize<Paciente>(novoPaciente));
            using (var data = new PacienteData())
                return View(data.ReadAll());

        }

        public IActionResult RelatorioProcedimento(int id)
        {



            //HttpContext.Session.SetString("relatorioconsulta", JsonSerializer.Serialize<int>(id));
            using (var data = new ItensUtilizadosData())
                return View(data.Read(id));

        }

        public IActionResult RelatorioMedico(Paciente novoPaciente)
        {


            HttpContext.Session.SetString("pacienterelatorio", JsonSerializer.Serialize<Paciente>(novoPaciente));




            using (var data = new MedicoData())
                return View(data.ReadAll());
        }



        public IActionResult Relatorio(Medico novomedico)
        {

            HttpContext.Session.SetString("medicorelatorio", JsonSerializer.Serialize<Medico>(novomedico));



            Consulta consurelato = new Consulta();

            var paciente = HttpContext.Session.GetString("pacienterelatorio");
            Paciente pacrelato = System.Text.Json.JsonSerializer.Deserialize<Paciente>(paciente);



            var medico = HttpContext.Session.GetString("medicorelatorio");
            Medico medrelato = System.Text.Json.JsonSerializer.Deserialize<Medico>(medico);



            consurelato.IdMedico = (int)medrelato.Id;
            consurelato.IdPaciente = (int)pacrelato.Id;


            using (var data = new ConsultaData())
                return View(data.ReadRelatorio(consurelato));
        }








        public IActionResult Finalizar(Medico novoMedico)
        {

            HttpContext.Session.SetString("medico", JsonSerializer.Serialize<Medico>(novoMedico));


            Consulta consulta = new Consulta();


            var paciente = HttpContext.Session.GetString("paciente");
            Paciente novopaciente = System.Text.Json.JsonSerializer.Deserialize<Paciente>(paciente);
            

            if (novopaciente.Id == null) {
                var paciente2 = HttpContext.Session.GetString("pacientevolta");
                novopaciente = System.Text.Json.JsonSerializer.Deserialize<Paciente>(paciente2);
            }
            else
            {

                HttpContext.Session.SetString("pacientevolta", JsonSerializer.Serialize<Paciente>(novopaciente));
            }


            var medico = HttpContext.Session.GetString("medico");
            Medico novomedico = System.Text.Json.JsonSerializer.Deserialize<Medico>(medico);


            var user = HttpContext.Session.GetString("user");
            Atendente atendente = System.Text.Json.JsonSerializer.Deserialize<Atendente>(user);

            Paciente novopaciente2 = new Paciente();

            using (var datapac = new PacienteData())
                novopaciente2 = datapac.Read((int)novopaciente.Id);
            using (var datamed = new MedicoData())
                novomedico = datamed.Read((int)novomedico.Id);
            using (var dataate = new AtendenteData())
                atendente = dataate.Read((int)atendente.Id);





            consulta.NomePaciente = novopaciente2.Nome;
            consulta.NomeMedico = novomedico.Nome;
            consulta.NomeAtendente = atendente.Nome;
            consulta.IdPaciente = (int)novopaciente2.Id;
            consulta.IdMedico = (int)novomedico.Id;
            consulta.IdAtendente = (int)atendente.Id;


            return View(consulta);
        }




        /* public IActionResult Index(string cpf)
         {
             using (var data = new ConsultaData())
                 return View(data.Read(cpf));
         }*/

        [HttpGet]
        public IActionResult Create()
        {
            Consulta consulta = new Consulta();

            var paciente = HttpContext.Session.GetString("paciente");
            Paciente novopaciente = System.Text.Json.JsonSerializer.Deserialize<Paciente>(paciente);



            var medico = HttpContext.Session.GetString("medico");
            Medico novomedico = System.Text.Json.JsonSerializer.Deserialize<Medico>(medico);


            var user = HttpContext.Session.GetString("user");
            Atendente atendente = System.Text.Json.JsonSerializer.Deserialize<Atendente>(user);



            using (var datapac = new PacienteData())
                novopaciente = datapac.Read((int)novopaciente.Id);
            using (var datamed = new MedicoData())
                novomedico = datamed.Read((int)novomedico.Id);
            using (var dataate = new AtendenteData())
                atendente = dataate.Read((int)atendente.Id);





            consulta.NomePaciente = novopaciente.Nome;
            consulta.NomeMedico = novomedico.Nome;
            consulta.NomeAtendente = atendente.Nome;
            consulta.IdPaciente = (int)novopaciente.Id;
            consulta.IdMedico = (int)novomedico.Id;
            consulta.IdAtendente = (int)atendente.Id;




            return View(consulta);

            
        }

       /* public IActionResult Criar()
        {
            Consulta consulta = new Consulta();

            var paciente = HttpContext.Session.GetString("paciente");
            Paciente novopaciente = System.Text.Json.JsonSerializer.Deserialize<Paciente>(paciente);
            


            var medico = HttpContext.Session.GetString("medico");
            Medico novomedico = System.Text.Json.JsonSerializer.Deserialize<Medico>(medico);
            

            var user = HttpContext.Session.GetString("user");
            Atendente atendente = System.Text.Json.JsonSerializer.Deserialize<Atendente>(user);
            


            using (var datapac = new PacienteData())
                novopaciente = datapac.Read((int)novopaciente.Id);
            using (var datamed = new MedicoData())
                novomedico = datamed.Read((int)novomedico.Id);
            using (var dataate = new AtendenteData())
                atendente = dataate.Read((int)atendente.Id);





            consulta.NomePaciente = novopaciente.Nome;
            consulta.NomeMedico = novomedico.Nome;
            consulta.NomeAtendente = atendente.Nome;
            consulta.IdPaciente = (int)novopaciente.Id;
            consulta.IdMedico = (int)novomedico.Id;
            consulta.IdAtendente = (int)atendente.Id;




            return View(consulta);
        }*/

        [HttpPost]
        public IActionResult Create(IFormCollection consulta)
        {
            try
            {
                /*Consulta consultanova = new Consulta();
                consultanova = consulta;


                var paciente = HttpContext.Session.GetString("paciente");
                Paciente novopaciente = new Paciente();
                novopaciente = System.Text.Json.JsonSerializer.Deserialize<Paciente>(paciente);


                var medico = HttpContext.Session.GetString("medico");
                Medico novomedico = new Medico();
                novomedico = System.Text.Json.JsonSerializer.Deserialize<Medico>(medico);

                var user = HttpContext.Session.GetString("user");
                Atendente atendente = new Atendente();
                atendente = System.Text.Json.JsonSerializer.Deserialize<Atendente>(user);




                consultanova.IdPaciente = (int)novopaciente.Id;
                consultanova.IdMedico = (int)novomedico.Id;
                consultanova.IdAtendente = (int)atendente.Id;*/

                var novoConsulta = new Consulta();
                novoConsulta.IdPaciente = Convert.ToInt32(consulta["IdPaciente"]);
                novoConsulta.IdMedico = Convert.ToInt32(consulta["IdMedico"]);
                novoConsulta.IdAtendente = Convert.ToInt32(consulta["IdAtendente"]);
                novoConsulta.Valor = Convert.ToInt32(consulta["Valor"]);
                novoConsulta.Status = (consulta["Status"]);


                if (novoConsulta.Valor < 0)
                {
                    ViewBag.Message = "Valor inválido.";
                    Consulta consulta3 = new Consulta(); 

                    var paciente = HttpContext.Session.GetString("paciente");
                    Paciente novopaciente = System.Text.Json.JsonSerializer.Deserialize<Paciente>(paciente);



                    var medico = HttpContext.Session.GetString("medico");
                    Medico novomedico = System.Text.Json.JsonSerializer.Deserialize<Medico>(medico);


                    var user = HttpContext.Session.GetString("user");
                    Atendente atendente = System.Text.Json.JsonSerializer.Deserialize<Atendente>(user);



                    using (var datapac = new PacienteData())
                        novopaciente = datapac.Read((int)novopaciente.Id);
                    using (var datamed = new MedicoData())

ProntoAtendimento/Views/Consulta/Atender.cshtml
@model List<Consulta>

@if (Model.Count == 0)
{
<div class="container-fluid mt-100">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Consultas</h5>
                </div>
                <div class="card-body cart">
                    <div class="col-sm-12 empty-cart-cls text-center">
                        <h3><strong>Nenhuma Consulta no momento.</strong></h3>

                        <a href="/home" class="btn btn-danger" data-abc="true">Sair</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> }
else
{

<br />


                <h5>Consultas</h5>

                                <table class="table table-hover rounded-top rounded-bottom shadow">


                                    <tr>
                                        <th>Nr</th>
                                        <th>Paciente</th>
                                        <th>Médico(a)</th>
                                        <th>Data</th>
                                        <th>Situação</th>
                                    </tr>


                                    @foreach (var cons in Model)

                                    {
                    <tr>
                        <td>@cons.Nr</td>
                        <td>@cons.Paciente.Nome</td>
                        <td>@cons.Medico.Nome</td>
                        <td>@cons.Data</td>
                        <td>@cons.Status</td>

                        <td>

                            <a class="btn btn-info" href="/consulta/update/@cons.Nr">Atender</a>


                        </td>
                    </tr>}

                                </table>
                                                <a href="/home" class="btn btn-sm btn-danger m-3" data-abc="true">Sair</a>}

ProntoAtendimento/Views/Consulta/Create.cshtml
@model Consulta

@if (ViewBag.Message != null)
{
<div class="alert alert-danger">@ViewBag.Message</div>}


<form asp-controller="Consulta" asp-action="Create" method="POST">

    <h5>Informe os Campos</h5>

    <div class="form-group">
        <label>IdMedico</label>
        <input asp-for="@Model.IdMedico" class="form-control" readonly="readonly" />
        <span asp-validation-for="IdMedico"></span>
    </div>
    <div class="form-group">
        <label>Medico</label>
        <input asp-for="@Model.NomeMedico" class="form-control" readonly="readonly" />
        <span asp-validation-for="NomeMedico"></span>
    </div>


    <div class="form-group">
        <label>IdPaciente</label>
        <input asp-for="@Model.IdPaciente" class="form-control" readonly="readonly" />
        <span asp-validation-for="IdPaciente"></span>
    </div>

    <div class="form-group">
        <label>Paciente</label>
        <input asp-for="@Model.NomePaciente" class="form-control" readonly="readonly" />
        <span asp-validation-for="NomePaciente"></span>
    </div>


    <div class="form-group">
        <label>IdAtendente</label>
        <input asp-for="@Model.IdAtendente" class="form-control" readonly="readonly" />
        <span asp-validation-for="IdAtendente"></span>
    </div>

    <div class="form-group">
        <label>Atendente</label>
        <input asp-for="@Model.NomeAtendente" class="form-control" readonly="readonly" />
        <span asp-validation-for="NomeAtendente"></span>
    </div>




    <div class="form-group">
        <label>Valor</label>
        <input asp-for="Valor" class="form-control" />
        <span asp-validation-for="Valor"></span>
    </div>

    <div class="form-group">
        <label>Status</label>
        <select asp-for="Status" class="form-control">
            <option value="1">Ativa</option>
            <option value="2">Encerrada</option>
            <option value="2">Aberta</option>

        </select>
    </div>





    <button class="btn btn-info cart-btn-transform mt-2 float-right m-2">Confirmar</button>
</form> 

ProntoAtendimento/Views/Consulta/Criar.cshtml
@model Consulta

<br />

@if (@Model == null)
{
<h3>@ViewBag.Mensagem</h3> }
            else
            {
                // <h3>@ViewBag.Mensagem @Model.Nome</h3>
<table class="table table-hover">


    <tr>
        <th>Medico</th>
        <th>Paciente</th>
        <th>Atendente</th>


    </tr>


    
    <tr>
        <td>@Model.NomeMedico</td>
        <td>@Model.NomePaciente</td>
        <td>@Model.NomeAtendente</td>

        <td>

            <a class="btn btn-sm btn-info" href="/consulta/create/@Model ">Selecionar</a>


        </td>
    </tr>
</table>}
<a class="btn btn-primary" href="/home/escolherconsulta">Voltar</a>

<a class="btn btn-primary" href="/medico/consulta">Continuar</a>

ProntoAtendimento/Views/Consulta/Erro.cshtml
<table class="table table-hover">

    <div style="text-align:center">

        <h3>Valor informado incorreto!</h3>
    </div>


    <div style="text-align:center">

        <p>Por favor, volte a tela inicial.</p>


       
        <a class="btn btn-outline-dark" href="/home/editar">Voltar</a>
    </div>

</table>

ProntoAtendimento/Views/Consulta/Fim.cshtml
@model Consulta


<table class="table table-hover">
    <tr>
        <th>Consulta finalizada</th>


    </tr>






</table>


<a class="btn btn-primary" href="/consulta/atender/">Voltar Para Lista de Consultas</a>

ProntoAtendimento/Views/Consulta/Finalizar.cshtml
@model Consulta


<table class="table table-hover">
    
    <center>
        <h4>
            A consulta será criada
        </h4>
    </center>
</table>
<div>
    
        
        <p> Paciente: @Model.NomePaciente </p>
        <p> Médico: @Model.NomeMedico</p>

    
</div>


<div>

    <a class="btn btn-primary btn-sm" href="/medico/consulta/">Voltar</a>
    <a class="btn btn-info btn-sm" href="/consulta/create/">Criar Consulta</a>


</div>

ProntoAtendimento/Views/Consulta/Index.cshtml
@model List<Consulta>

@if (Model.Count == 0)
{
<div class="container-fluid mt-100 ">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Consultas</h5>
                </div>
                <div class="card-body cart">
                    <div class="col-sm-12 empty-cart-cls text-center">
                        <h3><strong>Nenhuma Consulta aberta.</strong></h3>
                        
                        <a href="/home/editar" class="btn btn-danger m-3" data-abc="true">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> }
            else
            {


<br />

                @if (@Model == null)
                {
<h3>@ViewBag.Mensagem</h3> }
                else
                {

                    <h5>Lista de Consultas</h5>
<table class="table table-hover rounded-top rounded-bottom shadow" style="background-color:transparent">
    <tr>
        <th>Nr</th>
        <th>Paciente</th>
        <th>Médico(a)</th>
        <th>Data</th>
        <th>Situação</th>
    </tr>

    @foreach (var consulta in Model)
    {
<tr>
    <td>@consulta.Nr</td>
    <td>@consulta.Paciente.Nome</td>
    <td>@consulta.Medico.Nome</td>
    <td>@consulta.Data</td>
    <td>@consulta.Status</td>

    
</tr>}
</table>}
                                <a href="/home/inicial" class="btn btn-primary" data-abc="true">Voltar</a> }

ProntoAtendimento/Views/Consulta/Relatorio.cshtml
@model List<Consulta>

@if (Model.Count == 0)
{
<div class="container-fluid mt-100">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Relatórios</h5>
                </div>
                <div class="card-body cart">
                    <div class="col-sm-12 empty-cart-cls text-center">
                        <h3><strong>Nenhum Relatório encontrado</strong></h3>

                        <a href="/home/inicial" class="btn btn-primary" data-abc="true">Voltar</a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> }
            else
            {
<div class="container-fluid mt-100">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Relatório da Consulta</h5>
                </div>
                <div>
                    <table class="table table-hover rounded-top rounded-bottom shadow">
                        <tr>
                            <th>Id</th>
                            <th>Médico</th>
                            <th>Paciente</th>
                            <th>Data</th>
                            <th>Valor</th>
                            <th>Diagnostico</th>

                        </tr>
                        @foreach (var item in Model)
                        {
                    <tr>
                        <td>@item.Nr</td>
                        <td>@item.Medico.Nome</td>
                        <td>@item.Paciente.Nome</td>
                        <td>@item.Data</td>
                        <td>@item.Valor</td>
                        <td>@item.Diagnostico</td>
                        <td>
                            <a href="/consulta/relatorioprocedimento/@item.Nr" class="btn btn-sm btn-danger" >Procedimentos</a>
                        </td>
                    </tr>
                                        }

                    </table>
                </div>
            </div>
            <a href="/home/inicial" class="btn btn-info cart-btn-transform mt-2 float-right m-2"
               data-abc="true">
                Voltar
            </a>
            
        </div>
    </div>
</div>

                <script>function removidoBox() {
            alert("Item Removido Com Sucesso!");
        }</script>}

ProntoAtendimento/Views/Consulta/RelatorioMedico.cshtml
@model List<Medico>

<br />

@if (@Model == null)
{
<h3>@ViewBag.Mensagem</h3> }
            else
            {

    <h5>Selecione o Médico: </h5>
                // <h3>@ViewBag.Mensagem @Model.Nome</h3>
<table class="table table-hover rounded-top rounded-bottom shadow">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Endereço</th>
        <th>Telefone</th>
        <th>Status</th>

    </tr>

    @foreach (var medic in Model)
    {
<tr>
    <td>@medic.Id</td>
    <td>@medic.Nome</td>
    <td>@medic.Endereco</td>
    <td>@medic.Telefone</td>
    <td>@medic.Status</td>

    <td>

        <a class="btn btn-sm btn-info" href="/consulta/relatorio/@medic.Id">Selecionar</a>

    </td>
</tr>}
</table>}
<a class="btn btn-primary" href="/consulta/relatoriopaciente">Voltar</a>
<a class="btn btn-danger" href="/home">Sair</a>

ProntoAtendimento/Views/Consulta/RelatorioPaciente.cshtml
@model List<Paciente>

<br />

@if (@Model == null)
{
<h3>@ViewBag.Mensagem</h3> }
            else
            {
<h5>Selecione o Paciente: </h5>
                // <h3>@ViewBag.Mensagem @Model.Nome</h3>
<table class="table table-hover rounded-top rounded-bottom shadow">


    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Endereço</th>
        <th>Telefone</th>
        <th>Convenio</th>
        <th>Status</th>

    </tr>


    @foreach (var pacie in Model)

    {
<tr>
    <td>@pacie.Id</td>
    <td>@pacie.Nome</td>
    <td>@pacie.Endereco</td>
    <td>@pacie.Telefone</td>
    <td>@pacie.Convenio</td>
    <td>@pacie.Status</td>
    <td>

        <a class="btn btn-sm btn-info" href="/consulta/relatoriomedico/@pacie.Id ">Selecionar</a>


    </td>
</tr>}
</table>}
<a class="btn btn-primary" href="/home/inicial">Voltar</a>

ProntoAtendimento/Views/Consulta/RelatorioProcedimento.cshtml
@model List<ItensUtilizados>

@if (Model.Count == 0)
{
<div class="container-fluid mt-100">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Procedimentos</h5>
                </div>
                <div class="card-body cart">
                    <div class="col-sm-12 empty-cart-cls text-center">
                        <h3><strong>Nenhum Procedimento</strong></h3>

                        <a href="/procedimento/selection" class="btn btn-primary" data-abc="true">Escolher Procedimento</a>
                        <a href="/home" class="btn btn-sm btn-danger m-3" data-abc="true">Sair</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> }
            else
            {
<div class="container-fluid mt-100">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5>Procedimentos Utilizados</h5>
                </div>
                <div>
                    <table class="table table-hover rounded-top rounded-bottom shadow">
                        <tr>
                            
                            <th>Nome</th>
                            <th>Tipo</th>
                            <th>Valor</th>

                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
            
                                <td>@item.Procedimento.Nome</td>
                                <td>@item.Procedimento.Tipo</td>
                                <td>@item.Procedimento.Valor</td>

            
                            </tr>}
                    </table>
                </div>
            </div>
            <a href="/home/inicial" class="btn btn-info cart-btn-transform mt-2 float-right m-2"
               data-abc="true">
                Continuar
            </a>
            
        </div>
    </div>
</div>

                <script>
                    function removidoBox() {
                        alert("Item Removido Com Sucesso!");
                    }
                </script>}

ProntoAtendimento/Views/Consulta/Update.cshtml
@model Consulta

<form asp-controller="Consulta" asp-action="Update" method="POST">

    <h5>Atendimento</h5>


    <div class="form-group">
        <label>Status</label>
        <select asp-for="Status" class="form-control">
            <option value="1">Ativa</option>
            <option value="2">Encerrada</option>
            <option value="3">Aberta</option>
        </select>
    </div>


    <div class="form-group">
        <label>Diagnsotico</label>
        <input asp-for="Diagnostico" class="form-control" />
        <span asp-validation-for="Diagnostico"></span>
    </div>


    <div class="form-group">
        <button class="btn btn-outline-secondary">Atualizar Consulta</button>
    </div>
</form>

<a class="btn btn-info  cart-btn-transform mt-2 float-right m-2" href="/procedimento/selection">Procedimentos</a>
    